[mypy]
ignore_missing_imports = True
explicit_package_bases = True
exclude = (?x)(
    ^scripts/.*$
  )
disable_error_code = attr-defined,arg-type,assignment,return-value,misc,import-untyped,import-not-found,annotation-unchecked,operator,call-arg,var-annotated,type-var,no-untyped-def
